sudo: false
language: node_js

node_js:
  - "10"
  - "12"
  - "13"
  - "node"

script: npm run test

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    node: "node"
